# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 05:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 5, 12, 59, 560781, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
